version: '3.8'
services:
  currency-report:
    build: ./currency-report
    container_name: currency-report
    networks:
      - micronet
    ports:
      - "8100:8100"
    environment:
      - SERVICE_NAME=currency-report


  currency-history:
    build: ./currency-history
    container_name: currency-history
    networks:
      - micronet
    ports:
     - "8101:8101"
    environment:
      - SERVICE_NAME=currency-history


networks:
  micronet:
    driver: bridge